### ISSUE TITLE
报错：说ckpt没有model_checkpoint_path这个属性

### ISSUE THREAD

**Issue by dykhliww** [lc222/seq2seq_chatbot#11]
训练第一次没问题，再训练的时候chatbot.py文件中create_model（）函数中的47行语句   elif ckpt and tf.gfile.Exists(ckpt.model_checkpoint_path):出现的问题，请问这是什么原因

**Comment by yjyGo** [comment]
那是训练之后才有的，如果你重新训练，tmp文件夹清空，还有改decode这个变量的值，把chatbot.py的这行代码：
tf.app.flags.DEFINE_boolean("decode", True, "Set to True for interactive decoding.")
改成
tf.app.flags.DEFINE_boolean("decode", False, "Set to True for interactive decoding.")
就可以重新训练
如果测试，改为True就好了

**Comment by tangchen2** [comment]
其实 只要把ckpt.model_checkpoint_path的model_checkpoint_path删了就行了 因为tf.train.get_latest_checkpoint已经返回了checkpoint_path了

**Comment by KellyHwong** [comment]
修了这个bug，在pr
https://github.com/lc222/seq2seq_chatbot/pull/17
